services:
  app:
    build: .
    container_name: app
    command: "python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/code
    env_file: 
      - ./.env.dev
    restart: always
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:14-alpine
    container_name: db
    ports:
      - 5432:5432
    volumes:
      - custom_user_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=custom_user_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5


volumes:
  custom_user_data:
